name: 'Build Symfony App'
description: 'Builds and optionaly tests a Symfony app'

inputs:
  repository:
    description: 'Repository to fetch'
    required: false
    default: '${{ github.repository }}'
  build-webpack-assets:
    description: 'Whether to build webpack assets or not'
    required: false
    default: 'false'
  run-tests:
    description: 'Whether to run tests with PHPUnit or not'
    required: false
    default: 'false'
  cache-build:
    description: 'Whether to cache the build for reuse in different jobs.'
    required: false
    default: 'false'
  cache-key-prefix:
    description: 'Prefix to use for the cache key used for caching the build output.'
    required: false
    default: 'symfony-build-'

  lfs:
    description: 'Whether to download Git-LFS files'
    required: false
    default: 'false'

  php-version:
    description: 'PHP version to use'
    required: false
    default: '8.2'
  php-extensions:
    description: 'PHP extensions to install'
    required: false
    default: 'mbstring, xml, ctype, iconv, intl, pdo, pdo_mysql, dom, filter, gd, json'

  composer-options:
    description: 'Additional Composer options'
    required: false
    default: '--prefer-dist'
  composer-additional-dependencies:
    description: 'Additional Composer dependencies to install on build.'
    required: false
    default: ''

  symfony-environment:
    description: 'Symfony environment to build'
    required: false
    default: 'dev'

  github-token:
    description: 'Github Access Token'
    required: false
    default: ''

outputs:
  cache-key:
    description: Cache key for restoring build. Input `cache-build` has to be set to 'true'.
    value: ${{ steps.cache-key.outputs.cache-key }}

runs:
  using: 'composite'
  steps:
    # Setup PHP
    - uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ${{ inputs.php-extensions }}
        tools: composer, flex, symfony

    # Fetch the repo
    - uses: actions/checkout@v5
      with:
        repository: ${{ inputs.repository }}
        lfs: ${{ inputs.lfs }}

    # Setup .env.local
    - run: 'echo "APP_ENV=${{ inputs.symfony-environment }}" > .env.local'
      shell: bash

    # Cache Composer
    - id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT
      shell: bash
    - uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-

    # Auth Composer
    - if: ${{ inputs.github-token != '' }}
      run: "composer config --auth github-oauth.github.com ${{ inputs.github-token }}"
      shell: bash

    # Install dependencies with Composer
    - run: symfony composer install --no-interaction --no-progress --ansi ${{ inputs.composer-options }}
      shell: bash

    # Install additional dependencies
    - if: ${{ inputs.composer-additional-dependencies != '' }}
      run: symfony composer require ${{ inputs.composer-additional-dependencies }}
      shell: bash

    # Install Test-Pack, if required
    - if: ${{ inputs.run-tests == 'true' }}
      run: symfony composer require test
      shell: bash

    # Setup Node
    - if: ${{ inputs.build-webpack-assets == 'true' }}
      uses: actions/setup-node@v4

    # Install packages and build assets with NPM
    - if: ${{ inputs.build-webpack-assets == 'true' }}
      run: |
        npm install
        npm run build
      shell: bash

    # Run tests with PHPUnit
    - if: ${{ inputs.run-tests == 'true' }}
      run: symfony php bin/phpunit
      shell: bash

    - id: cache-key
      if: ${{ inputs.cache-build == 'true' }}
      run: echo "cache-key=${{ inputs.cache-key-prefix }}${{ github.run_id }}" >> $GITHUB_OUTPUT
      shell: bash

    - if: ${{ inputs.cache-build == 'true' }}
      uses: actions/cache/save@v4
      with:
        path: ./
        key: ${{ steps.cache-key.outputs.cache-key }}
