
name: Test Action

on: [ push ]

jobs:
  build-dev-app:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton
          run-tests: true