name: Test Action

on:
  push:
    paths:
      - '.github/**'
      - action.yml

env:
  SYMFONY_VERSION: "8.0"

jobs:
  build-dev:
    runs-on: ubuntu-latest
    outputs:
      cache-key: ${{ steps.build.outputs.cache-key }}
    steps:
      - id: build
        uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton
          branch: ${{ env.SYMFONY_VERSION }}
          cache-build: true

  # Check if the build was cached correctly and can be restored
  restore-cache:
    needs: build-dev
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache/restore@v6
        with:
          key: ${{ needs.build-dev.outputs.cache-key }}
          path: ./
          fail-on-cache-miss: true

  build-with-webpack:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton
          branch: ${{ env.SYMFONY_VERSION }}
          composer-additional-dependencies: webpack
          build-webpack-assets: true

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton
          branch: ${{ env.SYMFONY_VERSION }}
          run-tests: true
