
name: Test Action

on: [ push ]

jobs:
  build-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton

  build-with-webpack:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton
          composer-additional-dependencies: webpack
          build-webpack-assets: true

  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: ebitkov/build-symfony@main
        with:
          repository: symfony/skeleton
          run-tests: true